<?php

namespace AppBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @param $id
     * @return mixed
     */
    public function getMaxOrderValue()
    {
        $qb = $this->createQueryBuilder('v')
                   ->addSelect('v')
                   ->orderBy('v.ordre', 'DESC')
                   ->setMaxResults(1)
                   ->getQuery()
        ;
        return $qb->getOneOrNullResult();
    }

}
