homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:homepage }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

# logout
logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout}

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin/